//
//  ContentView.swift
//  world-flags
//
//  Created by Patrik Svensson on 2023-12-08.
//

import Foundation
import SwiftUI

struct ContentView: View {
    @State var searchText = ""

    let countries = [
        "af": "Afghanistan",
        "ax": "Åland",
        "al": "Albanien",
        "dz": "Algeriet",
        "as": "Amerikanska samoa",
        "ad": "Andorra",
        "ao": "Angola",
        "ai": "Anguilla",
        "aq": "Antarktis",
        "ag": "Antigua och barbuda",
        "ar": "Argentina",
        "am": "Armenien",
        "aw": "Aruba",
        "au": "Australien",
        "at": "Österrike",
        "az": "Azerbaijan",
        "bs": "Bahamas",
        "bh": "Bahrain",
        "bd": "Bangladesh",
        "bb": "Barbados",
        "be": "Belgien",
        "bz": "Belize",
        "bj": "Benin",
        "bm": "Bermuda",
        "bt": "Bhutan",
        "bo": "Bolivia, plurinational staten",
        "bq": "Bonaire, sint eustatius och saba",
        "ba": "Bosnien och hercegovina",
        "bw": "Botswana",
        "bv": "Bouvetön",
        "br": "Brasilien",
        "io": "Brittiska territoriet i indiska oceanen",
        "bn": "Brunei",
        "bg": "Bulgarien",
        "bf": "Burkina faso",
        "bi": "Burundi",
        "by": "Vitryssland",
        "kh": "Kambodja",
        "cm": "Kamerun",
        "ca": "Kanada",
        "cv": "Cap verde",
        "ky": "Caymanöarna",
        "cf": "Centralafrikanska republiken",
        "td": "Tchad",
        "cl": "Chile",
        "cn": "Kina",
        "cx": "Julön",
        "cc": "Cocos (keeling) islands",
        "co": "Colombia",
        "cu": "Cuba",
        "km": "Comoros",
        "cg": "Kongo",
        "cd": "Kongo, demokratiska republiken",
        "ck": "Cooköarna",
        "cr": "Costa rica",
        "hr": "Kroatien",
        "cw": "Curacao",
        "cy": "Cypern",
        "cz": "Tjeckien",
        "dk": "Danmark",
        "dj": "Djibouti",
        "dm": "Dominica",
        "do": "Dominikanska republiken",
        "ec": "Ecuador",
        "eg": "Egypten",
        "sv": "El salvador",
        "gq": "Ekvatorialguinea",
        "er": "Eritrea",
        "ee": "Estland",
        "et": "Etiopien",
        "fk": "Falklandsöarna (malvinas)",
        "fo": "Färöarna",
        "fj": "Fiji",
        "fi": "Finland",
        "fr": "Frankrike",
        "gf": "Franska guyana",
        "pf": "Franska polynesien",
        "tf": "Franska sydterritorierna",
        "ga": "Gabon",
        "gm": "Gambia",
        "ge": "Georgien",
        "de": "Tyskland",
        "gh": "Ghana",
        "gi": "London",
        "gr": "Grekland",
        "gl": "Grönland",
        "gd": "Grenada",
        "gp": "Guadeloupe",
        "gu": "Guam",
        "gt": "Guatemala",
        "gg": "Guernsey",
        "gn": "Guinea",
        "gw": "Guinea-bissau",
        "gy": "Guyana",
        "ht": "Haiti",
        "hm": "Heardön och mcdonaldöarna",
        "va": "Heliga stolen (vatikanstaten)",
        "hn": "Honduras",
        "hk": "Hong kong",
        "hu": "Ungern",
        "is": "Island",
        "in": "Indien",
        "id": "Indonesien",
        "iq": "Irak",
        "ie": "Irland",
        "im": "Ö av man",
        "il": "Israel",
        "it": "Italien",
        "ir": "Iran",
        "jm": "Jamaica",
        "jp": "Japan",
        "je": "Jersey",
        "jo": "Jordanien",
        "kz": "Kazakstan",
        "ke": "Kenya",
        "ki": "Kiribati",
        "kp": "Korea, Demokratiska Folkrepubliken",
        "kr": "Korea, republiken av",
        "kw": "Kuwait",
        "kg": "Kyrgyzstan",
        "la": "Laos folkdemokratiska republik",
        "lv": "Lettland",
        "lb": "Libanon",
        "ls": "Lesotho",
        "lr": "Liberia",
        "ly": "Libyen",
        "li": "Liechtenstein",
        "lt": "Litauen",
        "lu": "Luxemburg",
        "mo": "Macao",
        "mg": "Madagaskar",
        "mw": "Malawi",
        "my": "Malaysia",
        "mv": "Maldiverna",
        "ml": "Mali",
        "mt": "Malta",
        "mh": "Marshallöarna",
        "mq": "Martinique",
        "mr": "Mauretanien",
        "mu": "Mauritius",
        "yt": "Mayotte",
        "mx": "Mexico",
        "fm": "Mikronesien (federated states of)",
        "md": "Moldavien",
        "mc": "Monaco",
        "mn": "Mongoliet",
        "me": "Montenegro",
        "ms": "Montserrat",
        "ma": "Marocko",
        "mz": "Moçambique",
        "mm": "Myanmar",
        "na": "Namibia",
        "nr": "Nauru",
        "np": "Nepal",
        "nl": "Nederländerna",
        "nc": "Nya kaledonien",
        "nz": "Nya zeeland",
        "ni": "Nicaragua",
        "ne": "Niger",
        "ng": "Nigeria",
        "nu": "Niue",
        "nf": "Norfolk island",
        "mk": "Norra makedonien",
        "mp": "Nordmarianerna",
        "no": "Norge",
        "om": "Oman",
        "pk": "Pakistan",
        "pw": "Palau",
        "ps": "Palestina, state of",
        "pa": "Panama",
        "pg": "Papua nya guinea",
        "py": "Paraguay",
        "pe": "Peru",
        "ph": "Filippinerna",
        "pn": "Pitcairn",
        "pl": "Polen",
        "pt": "Portugal",
        "pr": "Puerto rico",
        "qa": "Qatar",
        "re": "Återförening",
        "ro": "Rumänien",
        "ru": "Ryssland",
        "rw": "Rwanda",
        "bl": "Saint barthelemy",
        "sh": "Sankta Helena, Ascension och Tristan da Cunha",
        "kn": "Saint kitts och nevis",
        "lc": "Saint lucia",
        "mf": "Saint martin (franska delen)",
        "pm": "Saint pierre och miquelon",
        "vc": "Saint vincent och grenadinerna",
        "ws": "Samoa",
        "sm": "San marino",
        "sa": "Saudiarabien",
        "sn": "Senegal",
        "rs": "Serbien",
        "sc": "Seychellerna",
        "sd": "Sudan",
        "sl": "Sierra leone",
        "sg": "Singapore",
        "sy": "Syrien",
        "sx": "Sint maarten (nederländska delen)",
        "sk": "Slovakien",
        "si": "Slovenien",
        "sb": "Salomonöarna",
        "so": "Somalia",
        "za": "Sydafrika",
        "gs": "Sydgeorgien och sydsandwichöarna",
        "ss": "Södra sudan",
        "es": "Spanien",
        "lk": "Sri lanka",
        "sr": "Suriname",
        "sj": "Svalbard och jan mayen",
        "se": "Sverige",
        "ch": "Schweiz",
        "st": "São tomé och príncipe",
        "tw": "Taiwan",
        "tj": "Tadzjikistan",
        "tz": "Tanzania av",
        "th": "Thailand",
        "tg": "Togo",
        "tk": "Tokelau",
        "tt": "Trinidad och tobago",
        "tn": "Tunisien",
        "tr": "Turkiet",
        "tm": "Turkmenistan",
        "tc": "Turks-och caicosöarna",
        "tv": "Tuvalu",
        "ug": "Uganda",
        "ua": "Ukraina",
        "ae": "Förenade arabemiraten",
        "gb": "Storbritannien",
        "us": "USA",
        "um": "Förenta staternas avlägset belägna öar",
        "uy": "Uruguay",
        "uz": "Uzbekistan",
        "vu": "Vanuatu",
        "ve": "Venezuela",
        "vn": "Vietnam",
        "vg": "Jungfruöarna, brittiska",
        "vi": "Amerikanska jungfruöarna",
        "wf": "Wallis och futuna",
        "eh": "Västra sahara",
        "ye": "Jemen",
        "zm": "Zambia",
        "zw": "Zimbabwe",
    ]
    
    var body: some View {
        NavigationStack {
            VStack {
                List {
                    ForEach(searchResults.sorted(by: <), id: \.key) { key, value in
                        Text(value).frame(maxWidth: .infinity, alignment: .center).bold()
                        Image(key).resizable().frame(height: 200).aspectRatio(contentMode: .fit)
                            .border(.gray)
                        Spacer()
                    }
                    .listRowSeparator(.hidden)
                }
                .navigationTitle("Adas flaggor")
            }
        }.searchable(text: $searchText, prompt: "Sök flagga") {
            if !searchText.isEmpty {
                ForEach(searchResults.sorted(by: <), id: \.value) { result in
                    Text(result.value).searchCompletion(result.value)
                }
            }
        }
    }
    
    // A computer property that returns the filtered search results
    var searchResults: [String: String] {
        if !searchText.isEmpty {
            return countries.filter { $1.starts(with: searchText) }
        }
        
        return countries
    }
}

#Preview {
    ContentView()
}
